std_dtoa: fix compile warnings
Fix warnings related to the aliasing of type-punned pointers by using
union instead of pointer dereferencing.

In file included from std_dtoa.c:7:
std_dtoa.c: In function 'fp_pow_10':
../inc/std_dtoa.h:71:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   71 | #define UINT64_TO_DOUBLE(u)      ( *( (double*) &(u) ) )
      |                                     ~~^~~~~~~~~~~~~~~~
std_dtoa.c:99:30: note: in expansion of macro 'UINT64_TO_DOUBLE'
   99 |       dRet = bNegative ? 0 : UINT64_TO_DOUBLE( ulInf );
      |                              ^~~~~~~~~~~~~~~~
std_dtoa.c: In function 'fp_check_special_cases':
../inc/std_dtoa.h:69:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   69 | #define DOUBLE_TO_UINT64(d)      ( *( (uint64*) &(d) ) )
      |                                     ~~^~~~~~~~~~~~~~~~
std_dtoa.c:157:15: note: in expansion of macro 'DOUBLE_TO_UINT64'
  157 |    ullValue = DOUBLE_TO_UINT64( dNumber );
      |               ^~~~~~~~~~~~~~~~
std_dtoa.c: In function 'std_dtoa_hex':
../inc/std_dtoa.h:69:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   69 | #define DOUBLE_TO_UINT64(d)      ( *( (uint64*) &(d) ) )
      |                                     ~~^~~~~~~~~~~~~~~~
std_dtoa.c:362:22: note: in expansion of macro 'DOUBLE_TO_UINT64'
  362 |    uint64 ullValue = DOUBLE_TO_UINT64( dNumber );
      |                      ^~~~~~~~~~~~~~~~

Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@oss.qualcomm.com>